<font style="font-weight: bold;"> IMPORTANT :</font> I am not gonna teach you here instead I am going to show the way how I learned this topics

### A Quick Intro about this Session 

* This course is hands-on driven with coding involving <font style="font-weight: bold;"> Python, Pandas, Numpy and Scikit-Learn Packages. </font>
* Editor: <font style="font-weight: bold;"> Jupyter Notebook </font>

* Classification : Categorizes a set of data into classes examples: Gender and Dog Breed Identification 
        * Structured Data: Excel, Releational Database and etc.
            * Unstrutured Data : Audio, Video, Picture and etc.

### Types of Classifcation

* Binary Classification - Eg: Gender Classifcation (Male\Female)
* Multi class classification - Eg: Dog Breed Classifcation (Different Breeds - German Shephard, Bull Dog, Poodle, and etc)
* Multi label classification - Eg: A news article can be about sports, a person, location at the same time
* Imblanced Classification - Imbalanced classification refers to classification tasks where the number of examples in each class is unequally distributed.

### Theory session is over here, let's move to Handon

In [91]:
import pandas as pd 
import numpy as np 

In [92]:
df = pd.read_csv('weather.csv')
df.head(3)

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0  12/1/2008   Albury     13.4     22.9       0.6          NaN       NaN   
1  12/2/2008   Albury      7.4     25.1       0.0          NaN       NaN   
2  12/3/2008   Albury     12.9     25.7       0.0          NaN       NaN   

  WindGustDir  WindGustSpeed WindDir9am  ... Humidity3pm  Pressure9am  \
0           W           44.0          W  ...        22.0       1007.7   
1         WNW           44.0        NNW  ...        25.0       1010.6   
2         WSW           46.0          W  ...        30.0       1007.6   

   Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  RISK_MM  \
0       1007.1       8.0       NaN     16.9     21.8         No      0.0   
1       1007.8       NaN       NaN     17.2     24.3         No      0.0   
2       1008.7       NaN       2.0     21.0     23.2         No      0.0   

   RainTomorrow  
0            No  
1            No  
2            No  

[3 rows x 24 columns]

In [93]:
#Shape of Dataframe
df.shape

(25000, 24)

In [94]:
# Identify the Target Column 
df.RainTomorrow

0        No
1        No
2        No
3        No
4        No
         ..
24995    No
24996    No
24997    No
24998    No
24999    No
Name: RainTomorrow, Length: 25000, dtype: object

In [95]:
# Imblance Check
df.RainTomorrow.value_counts()

No     19405
Yes     5595
Name: RainTomorrow, dtype: int64

## Data Analysis 

In [96]:
X = df.drop(['RainTomorrow','Date'], axis=1)
y = df.RainTomorrow

In [97]:
X.shape, y.shape

((25000, 22), (25000,))

## Preprocessing the Data

In [98]:
# IMPORTANT: As part this step, you have to convert entire dataframe to Integer/Float Data Type
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Location       25000 non-null  object 
 1   MinTemp        24669 non-null  float64
 2   MaxTemp        24824 non-null  float64
 3   Rainfall       24721 non-null  float64
 4   Evaporation    9432 non-null   float64
 5   Sunshine       6664 non-null   float64
 6   WindGustDir    21543 non-null  object 
 7   WindGustSpeed  21545 non-null  float64
 8   WindDir9am     21928 non-null  object 
 9   WindDir3pm     23267 non-null  object 
 10  WindSpeed9am   24428 non-null  float64
 11  WindSpeed3pm   23770 non-null  float64
 12  Humidity9am    24609 non-null  float64
 13  Humidity3pm    23936 non-null  float64
 14  Pressure9am    20172 non-null  float64
 15  Pressure3pm    20173 non-null  float64
 16  Cloud9am       14136 non-null  float64
 17  Cloud3pm       13815 non-null  float64
 18  Temp9a

In [99]:
X_cat = X.select_dtypes(include=[object])

In [100]:
X_cat

Location WindGustDir WindDir9am WindDir3pm RainToday
0       Albury           W          W        WNW        No
1       Albury         WNW        NNW        WSW        No
2       Albury         WSW          W        WSW        No
3       Albury          NE         SE          E        No
4       Albury           W        ENE         NW        No
...        ...         ...        ...        ...       ...
24995  Penrith          NE        SSE         NE        No
24996  Penrith          NE        ESE          N        No
24997  Penrith         ENE        NaN        ESE        No
24998  Penrith         NNE          S         NE        No
24999  Penrith          NE         NE         NE        No

[25000 rows x 5 columns]

In [101]:
X.RainToday.value_counts()

No     19197
Yes     5524
Name: RainToday, dtype: int64

In [102]:
int(False)

0

In [103]:
"no" == "yes"

False

In [104]:
colname = ["RainToday"]
X["RainToday"] = X[colname] == "Yes"

In [105]:
X.RainToday.value_counts()

False    19476
True      5524
Name: RainToday, dtype: int64

In [106]:
X.WindGustDir.value_counts()

NNE    1903
SW     1838
NE     1759
E      1590
WSW    1556
S      1553
SSW    1536
ENE    1436
W      1391
SSE    1213
SE     1192
WNW    1144
ESE    1058
N      1049
NW      740
NNW     585
Name: WindGustDir, dtype: int64

## One Hot Encoding

In [107]:
X.head(3)

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0   Albury     13.4     22.9       0.6          NaN       NaN           W   
1   Albury      7.4     25.1       0.0          NaN       NaN         WNW   
2   Albury     12.9     25.7       0.0          NaN       NaN         WSW   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0           44.0          W        WNW  ...         71.0         22.0   
1           44.0        NNW        WSW  ...         44.0         25.0   
2           46.0          W        WSW  ...         38.0         30.0   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1007.7       1007.1       8.0       NaN     16.9     21.8      False   
1       1010.6       1007.8       NaN       NaN     17.2     24.3      False   
2       1007.6       1008.7       NaN       2.0     21.0     23.2      False   

   RISK_MM  
0      0.0  
1      0.0  
2      0.0  

[3 rows x 22 columns]

In [108]:
type(X), X.shape

(pandas.core.frame.DataFrame, (25000, 22))

In [109]:
df_dumm = pd.get_dummies(X, columns=["Location","WindGustDir","WindDir9am","WindDir3pm"], prefix=["Location","WindGustDir","WindDir9am","WindDir3pm"])

In [110]:
df_dumm.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustSpeed', 'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am',
       'Humidity3pm', 'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm',
       'Temp9am', 'Temp3pm', 'RainToday', 'RISK_MM', 'Location_Albury',
       'Location_BadgerysCreek', 'Location_Cobar', 'Location_CoffsHarbour',
       'Location_Moree', 'Location_Newcastle', 'Location_NorahHead',
       'Location_NorfolkIsland', 'Location_Penrith', 'WindGustDir_E',
       'WindGustDir_ENE', 'WindGustDir_ESE', 'WindGustDir_N', 'WindGustDir_NE',
       'WindGustDir_NNE', 'WindGustDir_NNW', 'WindGustDir_NW', 'WindGustDir_S',
       'WindGustDir_SE', 'WindGustDir_SSE', 'WindGustDir_SSW',
       'WindGustDir_SW', 'WindGustDir_W', 'WindGustDir_WNW', 'WindGustDir_WSW',
       'WindDir9am_E', 'WindDir9am_ENE', 'WindDir9am_ESE', 'WindDir9am_N',
       'WindDir9am_NE', 'WindDir9am_NNE', 'WindDir9am_NNW', 'WindDir9am_NW',
       'WindDir9am_S', 'WindDir9am_SE', 'Wi

In [111]:
df_dumm.shape

(25000, 75)

# Simple Imputer

In [112]:
df_dumm.isna().sum()

MinTemp             331
MaxTemp             176
Rainfall            279
Evaporation       15568
Sunshine          18336
                  ...  
WindDir3pm_SSW        0
WindDir3pm_SW         0
WindDir3pm_W          0
WindDir3pm_WNW        0
WindDir3pm_WSW        0
Length: 75, dtype: int64

In [113]:
sample_df = pd.DataFrame([[7, 2, 3], [4, np.nan, 6], [10, 5, 9]])
import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(sample_df)

X = sample_df
print(imp_mean.transform(X))

[[ 7.   2.   3. ]
 [ 4.   3.5  6. ]
 [10.   5.   9. ]]


In [114]:
sample_df

0    1  2
0   7  2.0  3
1   4  NaN  6
2  10  5.0  9

In [115]:

import numpy as np
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
imp_mean.fit(df_dumm)

X = df_dumm
X_matrix = imp_mean.transform(X)

In [116]:
X_matrix, type(X_matrix)

(array([[13.4, 22.9,  0.6, ...,  0. ,  1. ,  0. ],
        [ 7.4, 25.1,  0. , ...,  0. ,  0. ,  1. ],
        [12.9, 25.7,  0. , ...,  0. ,  0. ,  1. ],
        ...,
        [18.3, 29.8,  0. , ...,  0. ,  0. ,  0. ],
        [17.5, 28.1,  0. , ...,  0. ,  0. ,  0. ],
        [15.4, 30.9,  0. , ...,  0. ,  0. ,  0. ]]),
 numpy.ndarray)

# Standardization

In [117]:
from sklearn.preprocessing import StandardScaler
data = [[5, 5], [5, 4], [10, 10], [10, 10]]
scaler = StandardScaler()
print(scaler.fit(data))

print(scaler.transform(data))


StandardScaler(copy=True, with_mean=True, with_std=True)
[[-1.         -0.81150267]
 [-1.         -1.17217053]
 [ 1.          0.9918366 ]
 [ 1.          0.9918366 ]]


In [118]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_matrix)
X = scaler.transform(X_matrix)


In [119]:
X

array([[ 0.01814869, -0.17899517, -0.21462107, ..., -0.23760696,
         4.54780906, -0.23277696],
       [-1.0146706 ,  0.18209479, -0.27669612, ..., -0.23760696,
        -0.2198861 ,  4.29595774],
       [-0.06791959,  0.28057387, -0.27669612, ..., -0.23760696,
        -0.2198861 ,  4.29595774],
       ...,
       [ 0.86161777,  0.95351424, -0.27669612, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 0.72390853,  0.67449019, -0.27669612, ..., -0.23760696,
        -0.2198861 , -0.23277696],
       [ 0.36242178,  1.13405922, -0.27669612, ..., -0.23760696,
        -0.2198861 , -0.23277696]])

## Split Train and test data 

In [129]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_label, test_label = train_test_split(X,y, test_size=.2)

train_data.shape, test_data.shape, train_label.shape, test_label.shape

((20000, 75), (5000, 75), (20000,), (5000,))

In [136]:
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

bag = BaggingClassifier()
kn = KNeighborsClassifier()
rn = RandomForestClassifier()
et = ExtraTreesClassifier()
dt = DecisionTreeClassifier()

bag.fit(train_data,train_label)
kn.fit(train_data,train_label)
rn.fit(train_data,train_label)
et.fit(train_data,train_label)
dt.fit(train_data,train_label)

bag.score(test_data,test_label), kn.score(test_data,test_label), rn.score(test_data,test_label), et.score(test_data,test_label), dt.score(test_data,test_label)


(1.0, 0.8124, 1.0, 0.938, 1.0)

### Upcoming Session 
#### Evaluate the Trained Model 
* RandomizedSearchCV()
* GridSearchCV()
* classification_report()
* confusion_matrix() 
* precision_score()
* recall_score()
* f1_score() 